import { Product, ShopProfile } from "../context/shopContext";

export const MOCK_SHOPS: ShopProfile[] = [
  {
    uid: "shop-kamala",
    businessName: "Kamala's Traditional Hearth",
    businessType: "Home Kitchen & Claypot Specialist",
    address: "42 Galle Road, Bambalapitiya",
    city: "Colombo",
    province: "Western",
    zipCode: "00400",
    phone: "+94 77 123 4567",
    email: "kamala.hearth@localplates.lk",
    rating: 4.9,
    photoURL: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=600&auto=format&fit=crop",
    userType: "seller",
    location: {
      latitude: 6.8912,
      longitude: 79.8587,
    },
  },
  {
    uid: "shop-fatima",
    businessName: "Fatima's Dum Biryani & Kebabs",
    businessType: "Dum Biryani Master & Mughlai",
    address: "18 Marine Drive, Kollupitiya",
    city: "Colombo",
    province: "Western",
    zipCode: "00300",
    phone: "+94 71 987 6543",
    email: "fatima.biryani@localplates.lk",
    rating: 5.0,
    photoURL: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?q=80&w=600&auto=format&fit=crop",
    userType: "seller",
    location: {
      latitude: 6.9124,
      longitude: 79.8519,
    },
  },
  {
    uid: "shop-mary",
    businessName: "Granny Mary's Dutch Burgher Kitchen",
    businessType: "Heritage Bakery & Lamprais",
    address: "75 Kynsey Road, Cinnamon Gardens",
    city: "Colombo",
    province: "Western",
    zipCode: "00700",
    phone: "+94 76 555 4321",
    email: "mary.burgher@localplates.lk",
    rating: 4.8,
    photoURL: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop",
    userType: "seller",
    location: {
      latitude: 6.9189,
      longitude: 79.8732,
    },
  },
  {
    uid: "shop-dilshan",
    businessName: "Dilshan's Village Wok & Kotthu",
    businessType: "Authentic Street Kotthu & Rotis",
    address: "12 Havelock Road",
    city: "Colombo",
    province: "Western",
    zipCode: "00500",
    phone: "+94 70 333 8899",
    email: "dilshan.wok@localplates.lk",
    rating: 4.9,
    photoURL: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?q=80&w=600&auto=format&fit=crop",
    userType: "seller",
    location: {
      latitude: 6.8834,
      longitude: 79.8654,
    },
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Claypot Jaffna Crab Curry",
    description: "Fresh lagoon crab simmered with toasted Jaffna spices, coconut milk, curry leaves, and tamarind.",
    price: 1650,
    quantity: 12,
    available: true,
    sellerId: "shop-kamala",
    sellerName: "Kamala's Traditional Hearth",
    sellerLocation: "Bambalapitiya, Colombo",
    type: "Rice & Curry",
    images: ["https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    name: "Woodfired Chicken Dum Biryani",
    description: "Fragrant basmati rice layered with marinated free-range chicken, saffron, ghee, and caramelized onions.",
    price: 1350,
    quantity: 20,
    available: true,
    sellerId: "shop-fatima",
    sellerName: "Fatima's Dum Biryani & Kebabs",
    sellerLocation: "Kollupitiya, Colombo",
    type: "Biryani",
    images: ["https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    name: "Authentic Banana Leaf Lamprais",
    description: "Dutch Burgher recipe with samba rice, mixed meat curry, frikkadels, blachan, and seeni sambal wrapped in scorched banana leaf.",
    price: 1500,
    quantity: 15,
    available: true,
    sellerId: "shop-mary",
    sellerName: "Granny Mary's Dutch Burgher Kitchen",
    sellerLocation: "Cinnamon Gardens, Colombo",
    type: "Rice & Curry",
    images: ["https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=800&auto=format&fit=crop"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    name: "Cheese Chicken Roast Paan Kotthu",
    description: "Fluffy wood-fired roast paan chopped on griddle with spicy roast chicken, fresh leeks, eggs, and melted mozzarella.",
    price: 1200,
    quantity: 25,
    available: true,
    sellerId: "shop-dilshan",
    sellerName: "Dilshan's Village Wok & Kotthu",
    sellerLocation: "Havelock Road, Colombo",
    type: "Short Eats",
    images: ["https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    name: "Crispy Pol Roti & Black Pork Curry",
    description: "Warm coconut flatbreads served with slow-cooked dark roasted black pepper pork curry and spicy lunu miris.",
    price: 950,
    quantity: 18,
    available: true,
    sellerId: "shop-kamala",
    sellerName: "Kamala's Traditional Hearth",
    sellerLocation: "Bambalapitiya, Colombo",
    type: "Short Eats",
    images: ["https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-6",
    name: "Kithul Jaggery Watalappam Bowl",
    description: "Traditional steamed coconut custard infused with pure Sinharaja kithul treacle, cardamom, and toasted cashews.",
    price: 650,
    quantity: 30,
    available: true,
    sellerId: "shop-mary",
    sellerName: "Granny Mary's Dutch Burgher Kitchen",
    sellerLocation: "Cinnamon Gardens, Colombo",
    type: "Desserts",
    images: ["https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=800&auto=format&fit=crop"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-7",
    name: "Handmade Artisanal Angus Burger",
    description: "Juicy hand-formed beef patty with caramelized shallots, aged cheddar, crisp greens, and secret house sauce.",
    price: 1450,
    quantity: 14,
    available: true,
    sellerId: "shop-dilshan",
    sellerName: "Dilshan's Village Wok & Kotthu",
    sellerLocation: "Havelock Road, Colombo",
    type: "Burger",
    images: ["https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=800&auto=format&fit=crop"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod-8",
    name: "Seafood Aglio Olio Noodles",
    description: "Tossed noodles with fresh prawns, calamari, garlic slivers, chili flakes, and virgin olive oil.",
    price: 1300,
    quantity: 16,
    available: true,
    sellerId: "shop-fatima",
    sellerName: "Fatima's Dum Biryani & Kebabs",
    sellerLocation: "Kollupitiya, Colombo",
    type: "Noodles",
    images: ["https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=800&auto=format&fit=crop"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
